spring.application.name=cloud-pocket-api
server.port=${PORT:8080}
server.servlet.context-path=/api/v1.0

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=cloudsharedb

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}